media:
  input: images
  output: /images

content:
  - name: site
    label: Site Settings
    type: file
    path: content/site.json
    format: json

    fields:
      - name: hero
        label: Hero
        type: object
        fields:
          - name: eyebrow
            label: Eyebrow
            type: string

          - name: heading
            label: Heading
            type: string

          - name: description
            label: Description
            type: text

  - name: projects
    label: Portfolio Projects
    type: file
    path: content/projects.json
    format: json
    list: true

    fields:
      - name: title
        label: Project Title
        type: string
        required: true

      - name: description
        label: Description
        type: text

      - name: image
        label: Project Image
        type: image

      - name: github
        label: GitHub URL
        type: string

      - name: tags
        label: Tech Stack
        type: string
        list: true